services:
  frostfire-forge:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.prod
    container_name: frostfire-forge-prod
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ../../.env.production:/app/.env.production:ro
    env_file:
      - ../../.env.production