services:
  frostfire-forge:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.prod
    container_name: frostfire-forge-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../../.env.production:/app/.env.production:ro
    env_file:
      - ../../.env.production
    networks:
      - frostfire-network-prod

networks:
  frostfire-network-prod:
    driver: bridge