services:
  frostfire-forge-dev:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile.dev
    container_name: frostfire-forge-dev
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.development
    volumes:
      - ../../src/certs:/app/certs:ro
      - ../../src/logs:/app/logs
      - ../../config:/app/config
    networks:
      - frostfire-network-dev

networks:
  frostfire-network-dev:
    driver: bridge
