services:
  frostfire-forge-dev:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile.dev
    container_name: frostfire-forge-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql-dev
      DATABASE_PORT: 3306
    volumes:
      - ../../.env.development:/app/.env.development:ro
    env_file:
      - ../../.env.development
    networks:
      - gateway-network-dev

networks:
  gateway-network-dev:
    driver: bridge
